# Generated by Django 5.2.4 on 2025-08-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_approved_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
        migrations.AddField(
            model_name='post',
            name='archivo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
