# Generated by Django 5.2.4 on 2025-08-29 00:02

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_comment_approved_comment_post_archivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_date']},
        ),
        migrations.AlterField(
            model_name='post',
            name='archivo',
            field=models.FileField(blank=True, upload_to='posts/', validators=[blog.models.validate_file_extension]),
        ),
    ]
